version: '3.9'

services:
  api-service:
    container_name: api-service
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
    ports:
      - 8080:3000
    depends_on:
      - redis
    restart: on-failure
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data/redis
volumes:
  redis_data:
