version: '3.9'

services:
  api-service:
    container_name: api-service
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
    ports:
      - 80:${APP_PORT}
    depends_on:
      - redis
    restart: on-failure
  # redis:
  #   image: redis:7.0
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis_data:/data/redis
  # redis-commander:
  #   container_name: redis-commander
  #   hostname: redis-commander
  #   image: ghcr.io/joeferner/redis-commander:latest
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   ports:
  #     - "8081:8081"
# volumes:
  # redis_data:
