export const USER_REPOSITORY = 'USER_REPOSITORY';
export const KYC_REPOSITORY = 'KYC_RESPOSITORY';
export const BUSINESS_TYPE_REPOSITORY = 'BUSINESS_TYPE_REPOSITORY';
export const BUSINESS_ENTITY_REPOSITORY = 'BUSINESS_ENTITY_REPOSITORY';
export const BUSINESS_INFORMATION_REPOSITORY =
  'BUSINESS_INFORMATION_REPOSITORY';
export const FINANCIAL_INFORMATION_REPOSITORY =
  'FINANCIAL_INFORMATION_REPOSITORY';
export const SUPORTED_BANK_PROVIDER_COUNTRIES =
  'SUPORTED_BANK_PROVIDER_COUNTRIES';
export const SUPORTED_BANK_PROVIDER = 'SUPORTED_BANK_PROVIDER';
export const FINANCIAL_CONNECT_PROVIDER = 'FINANCIAL_CONNECT_PROVIDER';
export const SOFTWARE_CONNECT_PROVIDER = 'SOFTWARE_CONNECT_PROVIDER';
export const USER_SESSION = 'USER_SESSION';
// export const FINANCIAL_REQUIREMENT = 'FINIANCIAL_REQUIREMENT';
export const BUSINESS_OWNER = 'BUSINESS_OWNER';
export const PATNER_REPOSITORY = 'PATNER_REPOSITORY';
export const FUNDING_REQUEST = 'FUNDING_REQUEST';
