export const USER_REPOSITORY = 'USER_REPOSITORY';
export const KYC_REPOSITORY = 'KYC_RESPOSITORY';
export const BUSINESS_TYPE_REPOSITORY = 'BUSINESS_TYPE_REPOSITORY';
export const BUSINESS_ENTITY_REPOSITORY = 'BUSINESS_ENTITY_REPOSITORY';
export const BUSINESS_INFORMATION_REPOSITORY = 'BUSINESS_INFORMATION_REPOSITORY';

